#!/bin/zsh

#Taken from: https://wiki.archlinux.org/title/User:Altercation/Bullet_Proof_Arch_Install

DRIVE=$1
export o=defaults,x-mount.mkdir
export o_btrfs=$o,compress=lzo,ssd,noatime

sgdisk --clear \
    --new=1:0:+550MiB --typecode=1:ef00 --change-name=1:EFI \
    --new=2:0:0 --typecode=3:8300 --change-name=3:cryptsystem $DRIVE

mkfs.fat -F32 -n EFI /dev/disk/by-partlabel/EFI

cryptsetup luksFormat --align-payload=8192 --cipher=aes-xts-plain64 --hash=sha512 --key-size=512 \
    --iter-time=3000 --verify-passphrase /dev/disk/by-partlabel/cryptsystem

cryptsetup open /dev/disk/by-partlabel/cryptsetup system

mount -t btrfs LABEL=system /mnt

btrfs subvolume create /mnt/@root
btrfs subvolume create /mnt/@home
btrfs subvolume create /mnt/@snapshots

umount -R /mnt

mount -t btrfs -o subvol=@root,$o_btrfs LABEL=system /mnt
mount -t btrfs -o subvol=@home,$o_btrfs LABEL=system /mnt/home
mount -t btrfs -o subvol=@snapshots,$o_btrfs LABEL=system /mnt/.snapshots