#!/bin/zsh

#Taken from: https://wiki.archlinux.org/title/User:Altercation/Bullet_Proof_Arch_Install

DRIVE=$1

export o=defaults,x-mount.mkdir
export o_btrfs=$o,compress=lzo,ssd,noatime

echo Creating partitions...

sgdisk --clear \
    --new=1:0:+550MiB --typecode=1:ef00 --change-name=1:EFI \
    --new=2:0:0 --typecode=2:8300 --change-name=2:crypt-system $DRIVE

echo Formatting partitions...

mkfs.fat -F32 -n EFI /dev/disk/by-partlabel/EFI

cryptsetup luksFormat --align-payload=8192 --cipher=aes-xts-plain64 --hash=sha512 --key-size=512 \
    --iter-time=3000 --verify-passphrase /dev/disk/by-partlabel/crypt-system

cryptsetup open /dev/disk/by-partlabel/cryp-system system

mkfs.btrfs -f --label system /dev/mapper/system

echo Mounting partitons and creating BTRFS subvolumes...
mount -t btrfs LABEL=system /mnt
btrfs subvolume create /mnt/@root
btrfs subvolume create /mnt/@home
btrfs subvolume create /mnt/@snapshots
btrfs subvolume create /mnt/@logs
btrfs subvolume create /mnt/@pkgs
btrfs subvolume create /mnt/@srv
btrfs subvolume create /mnt/@tmp

echo Unmounting partition and mounting subvolumes...
umount -R /mnt
mount -t btrfs -o subvol=@root,$o_btrfs LABEL=system /mnt
mount -t btrfs -o subvol=@home,$o_btrfs LABEL=system /mnt/home
mount -t btrfs -o subvol=@snapshots,$o_btrfs LABEL=system /mnt/.snapshots
mount -t btrfs -o subvol=@logs,$o_btrfs LABEL=system /mnt/var/log
mount -t btrfs -o subvol=@pkgs,$o_btrfs LABEL=system /mnt/var/cache/pacman/pkg
mount -t btrfs -o subvol=@srv,$o_btrfs LABEL=system /mnt/srv
mount -t btrfs -o subvol=@tmp,$o_btrfs LABEL=system /mnt/tmp

echo Mounting bootloader partition...
mkdir /mnt/boot
mount LABEL=EFI /mnt/boot

echo Installing system...
pacstrap -i /mnt base base-devel zsh grml-zsh-config nano wget git btrfs-progs linux linux-firmware openssh 

echo Generating fstab...
genfstab -Up /mnt << /mnt/etc/fstab

#Chroot into new install
sudo arch-chroot /mnt /bin/zsh << "EOT"

#Add user admin and set initial password to 'admin'
useradd -m -G wheel,storage,power,users,input -s /bin/zsh $1
echo -e "$2\n$2" | passwd $1

#Make user admin a sudoer
echo $1'  ALL=(ALL:ALL) ALL' >> /etc/sudoers

EOT

