#!/bin/zsh

sudo ./create_tpm win11tpm &

sudo qemu-system-x86_64 -enable-kvm -M pc-i440fx-6.1 -cpu qemu64 -smp cores=12 -m 24576 \
        -bios /usr/share/edk2-ovmf/x64/OVMF.fd \
        -drive if=pflash,format=raw,readonly=on,file=/usr/share/edk2-ovmf/x64/OVMF_CODE.fd \
        -drive if=pflash,format=raw,file=/home/nickobelic1999/win11_efi_vars.fd \
        -device vfio-pci,host=43:00.0 \
        -device vfio-pci,host=43:00.1 \
        -device vfio-pci,host=41:00.0 \
        -vga vmware \
        -chardev socket,id=chrtpm,path=/tmp/win11tpm/swtpm-sock \
        -tpmdev emulator,id=tpm0,chardev=chrtpm -device tpm-tis,tpmdev=tpm0 \
        -net nic,model=e1000 \
        -net user,hostfwd=tcp::3389-:3389 \
        -cdrom /Volumes/dataStore/operatingSystems/Windows_x64/Win11.iso \
        -vnc :1
