#!/bin/zsh

./createTPM win11tpm &

sudo qemu-system-x86_64 -enable-kvm -M pc-i440fx-6.1 -cpu host -smp cores=8 -m 16384 -hda /dev/nvme0n1 \
        -bios /usr/share/edk2-ovmf/x64/OVMF.fd \
	-drive if=pflash,format=raw,readonly=on,file=/usr/share/edk2-ovmf/x64/OVMF_CODE.fd \
	-drive if=pflash,format=raw,file=/home/nickobelic1999/win11_efi_vars.fd \
	-vga vmware \
        -netdev tap,id=mynet0,ifname=tap0,script=no,downscript=no \
	-device e1000,netdev=mynet0 \
	-chardev socket,id=chrtpm,path=/tmp/win11tpm/swtpm-sock \
	-tpmdev emulator,id=tpm0,chardev=chrtpm -device tpm-tis,tpmdev=tpm0 \
	-cdrom /home/nickobelic1999/Win11.iso \
	-vnc :1 -boot d
