#!/bin/zsh -x

export VM_NAME=$1
export VM_PATH=/Volumes/machines/@$1

sudo qemu-system-x86_64 -enable-kvm -M pc -cpu host -smp cores=8 -m 16384 \
	-hda $VM_PATH/$VM_NAME.qcow \
        -bios /usr/share/edk2-ovmf/x64/OVMF.fd \
        -drive if=pflash,format=raw,readonly=on,file=/usr/share/edk2-ovmf/x64/OVMF_CODE.fd \
        -drive if=pflash,format=raw,file=$VM_PATH/$VM_NAME"_efi_vars.fd" \
        -device e1000,netdev=network0 -netdev tap,id=network0,ifname=tap1,script=no,downscript=no,vhost=on \
	-vnc :0 -boot d\
        -cdrom $2

